#!/bin/bash -e

codedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PATH="$codedir/internals/:$PATH"

usage()
{
command=${0##*/}
cat <<EOF
usage: $command [a] [task] [name]
Examples:
    $command
    $command feed the cat
EOF
}

if [[ -z "$TODOFILE" ]]
then
    echo_in_red "environment variable TODOFILE must be set"
    exit 1
elif [[ $# -eq 1 && ( "$1" = '-h' || "$1" = '--help' ) ]]
then
    usage
    exit 0
else
    touch "$TODOFILE"
    if [[ $# -eq 0 ]]
    then
        show_todo
    else
        if grep "$*$" "$TODOFILE"
        then
            echo_in_red '!! exact duplicate !!'
            show_todo | grep --color=always "$*"
        else
            echo "$*" >> "$TODOFILE"
            echo "+ $*; $(date)" | to_todo_history_file
            show_todo
        fi
    fi
fi
